# Documentation
# Add Documentation

language: swift
osx_image: xcode11.4

cache: cocoapods

install:
  - brew update
  - gem install bundler
  - bundle update --bundler
  - bundle install
  - bundle exec pod repo update
#  - bundle exec pod install

script:
  - bundle exec fastlane test