name: Pull Request
on:
  pull_request:
    branches:
      - master
jobs:
  deploy:
    name: Testing Components
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Install gems
        run: bundle install
      - name: Pod repo update
        run: bundle exec pod repo update
      - name: Select XCode 11.4
        run: sudo xcode-select -switch /Applications/Xcode_11.4.app
      - name: Unit tests
        if: success()
        run: bundle exec fastlane test
